import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-investment-fund-expense-allocation-control",
  "engine": "recovery",
  "title": "Investment Fund Expense Allocation Control",
  "shortTitle": "Investment Fund Expense Allocation Control",
  "tagline": "Prevent prohibited or inequitable allocation of operating, deal, compliance, and shared expenses across funds and the manager.",
  "industry": "Asset Management Compliance",
  "buyer": "Fund managers, boards, and investors",
  "uiPort": 4674,
  "apiPort": 5674,
  "accent": "#7e22ce",
  "currency": "USD",
  "primaryOutcome": "Investment Fund Expense Allocation Control converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect fund documents, allocation policies, invoices, time records, vendor services, fund assets, investor classes, co-investments, broken deals, reimbursements, and NAV entries in one accountable workflow. Prevent prohibited or inequitable allocation of operating, deal, compliance, and shared expenses across funds and the manager.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Investment Fund Expense Allocation Control evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("allocation-policy-library","IFE01","Allocation policy library","Execute allocation policy library using fund documents, allocation policies, invoices, time records, vendor services, fund assets, investor classes, co-investments, broken deals, reimbursements, and NAV entries.","Produce a governed allocation policy library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Expense / Fund Complex","text","Expense / Fund Complex · Standard Case"],["caseReference","Allocation policy library Reference","text","IFE01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",933750],["supportedAmount","Evidence-Supported Amount","currency",784350],["domainDriver","Expense Category","select","Fund expense",["Fund expense","Manager expense","Shared expense"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Allocation policy library case","Fund entity registry case","Vendor invoice ingestion case","Expense category classification case","Manager versus fund test case"]}),
feature("fund-entity-registry","IFE02","Fund entity registry","Execute fund entity registry using fund documents, allocation policies, invoices, time records, vendor services, fund assets, investor classes, co-investments, broken deals, reimbursements, and NAV entries.","Produce a governed fund entity registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Expense / Fund Complex","text","Expense / Fund Complex · Standard Case"],["caseReference","Fund entity registry Reference","text","IFE02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",933750],["supportedAmount","Evidence-Supported Amount","currency",784350],["domainDriver","Expense Category","select","Fund expense",["Fund expense","Manager expense","Shared expense"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Allocation policy library case","Fund entity registry case","Vendor invoice ingestion case","Expense category classification case","Manager versus fund test case"]}),
feature("vendor-invoice-ingestion","IFE03","Vendor invoice ingestion","Execute vendor invoice ingestion using fund documents, allocation policies, invoices, time records, vendor services, fund assets, investor classes, co-investments, broken deals, reimbursements, and NAV entries.","Produce a governed vendor invoice ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Expense / Fund Complex","text","Expense / Fund Complex · Standard Case"],["caseReference","Vendor invoice ingestion Reference","text","IFE03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",933750],["supportedAmount","Evidence-Supported Amount","currency",784350],["domainDriver","Expense Category","select","Fund expense",["Fund expense","Manager expense","Shared expense"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Allocation policy library case","Fund entity registry case","Vendor invoice ingestion case","Expense category classification case","Manager versus fund test case"]}),
feature("expense-category-classification","IFE04","Expense category classification","Execute expense category classification using fund documents, allocation policies, invoices, time records, vendor services, fund assets, investor classes, co-investments, broken deals, reimbursements, and NAV entries.","Produce a governed expense category classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Expense / Fund Complex","text","Expense / Fund Complex · Standard Case"],["caseReference","Expense category classification Reference","text","IFE04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",933750],["supportedAmount","Evidence-Supported Amount","currency",784350],["domainDriver","Expense Category","select","Fund expense",["Fund expense","Manager expense","Shared expense"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Allocation policy library case","Fund entity registry case","Vendor invoice ingestion case","Expense category classification case","Manager versus fund test case"]}),
feature("manager-versus-fund-test","IFE05","Manager versus fund test","Execute manager versus fund test using fund documents, allocation policies, invoices, time records, vendor services, fund assets, investor classes, co-investments, broken deals, reimbursements, and NAV entries.","Produce a governed manager versus fund test decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Expense / Fund Complex","text","Expense / Fund Complex · Standard Case"],["caseReference","Manager versus fund test Reference","text","IFE05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",933750],["supportedAmount","Evidence-Supported Amount","currency",784350],["domainDriver","Expense Category","select","Fund expense",["Fund expense","Manager expense","Shared expense"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Allocation policy library case","Fund entity registry case","Vendor invoice ingestion case","Expense category classification case","Manager versus fund test case"]}),
feature("shared-service-allocation","IFE06","Shared service allocation","Execute shared service allocation using fund documents, allocation policies, invoices, time records, vendor services, fund assets, investor classes, co-investments, broken deals, reimbursements, and NAV entries.","Produce a governed shared service allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Expense / Fund Complex","text","Expense / Fund Complex · Standard Case"],["caseReference","Shared service allocation Reference","text","IFE06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",933750],["supportedAmount","Evidence-Supported Amount","currency",784350],["domainDriver","Expense Category","select","Fund expense",["Fund expense","Manager expense","Shared expense"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Allocation policy library case","Fund entity registry case","Vendor invoice ingestion case","Expense category classification case","Manager versus fund test case"]}),
feature("time-record-allocation","IFE07","Time-record allocation","Execute time-record allocation using fund documents, allocation policies, invoices, time records, vendor services, fund assets, investor classes, co-investments, broken deals, reimbursements, and NAV entries.","Produce a governed time-record allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Expense / Fund Complex","text","Expense / Fund Complex · Standard Case"],["caseReference","Time-record allocation Reference","text","IFE07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",933750],["supportedAmount","Evidence-Supported Amount","currency",784350],["domainDriver","Expense Category","select","Fund expense",["Fund expense","Manager expense","Shared expense"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Allocation policy library case","Fund entity registry case","Vendor invoice ingestion case","Expense category classification case","Manager versus fund test case"]}),
feature("broken-deal-allocation","IFE08","Broken-deal allocation","Execute broken-deal allocation using fund documents, allocation policies, invoices, time records, vendor services, fund assets, investor classes, co-investments, broken deals, reimbursements, and NAV entries.","Produce a governed broken-deal allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Expense / Fund Complex","text","Expense / Fund Complex · Standard Case"],["caseReference","Broken-deal allocation Reference","text","IFE08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",933750],["supportedAmount","Evidence-Supported Amount","currency",784350],["domainDriver","Expense Category","select","Fund expense",["Fund expense","Manager expense","Shared expense"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Allocation policy library case","Fund entity registry case","Vendor invoice ingestion case","Expense category classification case","Manager versus fund test case"]}),
feature("co-investment-treatment","IFE09","Co-investment treatment","Execute co-investment treatment using fund documents, allocation policies, invoices, time records, vendor services, fund assets, investor classes, co-investments, broken deals, reimbursements, and NAV entries.","Produce a governed co-investment treatment decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Expense / Fund Complex","text","Expense / Fund Complex · Standard Case"],["caseReference","Co-investment treatment Reference","text","IFE09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",933750],["supportedAmount","Evidence-Supported Amount","currency",784350],["domainDriver","Expense Category","select","Fund expense",["Fund expense","Manager expense","Shared expense"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Allocation policy library case","Fund entity registry case","Vendor invoice ingestion case","Expense category classification case","Manager versus fund test case"]}),
feature("cross-fund-allocation","IFE10","Cross-fund allocation","Execute cross-fund allocation using fund documents, allocation policies, invoices, time records, vendor services, fund assets, investor classes, co-investments, broken deals, reimbursements, and NAV entries.","Produce a governed cross-fund allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Expense / Fund Complex","text","Expense / Fund Complex · Standard Case"],["caseReference","Cross-fund allocation Reference","text","IFE10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",933750],["supportedAmount","Evidence-Supported Amount","currency",784350],["domainDriver","Expense Category","select","Fund expense",["Fund expense","Manager expense","Shared expense"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Allocation policy library case","Fund entity registry case","Vendor invoice ingestion case","Expense category classification case","Manager versus fund test case"]}),
feature("class-level-allocation","IFE11","Class-level allocation","Execute class-level allocation using fund documents, allocation policies, invoices, time records, vendor services, fund assets, investor classes, co-investments, broken deals, reimbursements, and NAV entries.","Produce a governed class-level allocation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Expense / Fund Complex","text","Expense / Fund Complex · Standard Case"],["caseReference","Class-level allocation Reference","text","IFE11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",933750],["supportedAmount","Evidence-Supported Amount","currency",784350],["domainDriver","Expense Category","select","Fund expense",["Fund expense","Manager expense","Shared expense"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Allocation policy library case","Fund entity registry case","Vendor invoice ingestion case","Expense category classification case","Manager versus fund test case"]}),
feature("policy-exception-workflow","IFE12","Policy exception workflow","Execute policy exception workflow using fund documents, allocation policies, invoices, time records, vendor services, fund assets, investor classes, co-investments, broken deals, reimbursements, and NAV entries.","Produce a governed policy exception workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Expense / Fund Complex","text","Expense / Fund Complex · Standard Case"],["caseReference","Policy exception workflow Reference","text","IFE12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",933750],["supportedAmount","Evidence-Supported Amount","currency",784350],["domainDriver","Expense Category","select","Fund expense",["Fund expense","Manager expense","Shared expense"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Allocation policy library case","Fund entity registry case","Vendor invoice ingestion case","Expense category classification case","Manager versus fund test case"]}),
feature("reimbursement-calculation","IFE13","Reimbursement calculation","Execute reimbursement calculation using fund documents, allocation policies, invoices, time records, vendor services, fund assets, investor classes, co-investments, broken deals, reimbursements, and NAV entries.","Produce a governed reimbursement calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Expense / Fund Complex","text","Expense / Fund Complex · Standard Case"],["caseReference","Reimbursement calculation Reference","text","IFE13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",933750],["supportedAmount","Evidence-Supported Amount","currency",784350],["domainDriver","Expense Category","select","Fund expense",["Fund expense","Manager expense","Shared expense"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Allocation policy library case","Fund entity registry case","Vendor invoice ingestion case","Expense category classification case","Manager versus fund test case"]}),
feature("nav-correction-reconciliation","IFE14","NAV correction reconciliation","Execute nav correction reconciliation using fund documents, allocation policies, invoices, time records, vendor services, fund assets, investor classes, co-investments, broken deals, reimbursements, and NAV entries.","Produce a governed nav correction reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Expense / Fund Complex","text","Expense / Fund Complex · Standard Case"],["caseReference","NAV correction reconciliation Reference","text","IFE14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",933750],["supportedAmount","Evidence-Supported Amount","currency",784350],["domainDriver","Expense Category","select","Fund expense",["Fund expense","Manager expense","Shared expense"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Allocation policy library case","Fund entity registry case","Vendor invoice ingestion case","Expense category classification case","Manager versus fund test case"]}),
feature("fund-expense-analytics","IFE15","Fund expense analytics","Execute fund expense analytics using fund documents, allocation policies, invoices, time records, vendor services, fund assets, investor classes, co-investments, broken deals, reimbursements, and NAV entries.","Produce a governed fund expense analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Expense / Fund Complex","text","Expense / Fund Complex · Standard Case"],["caseReference","Fund expense analytics Reference","text","IFE15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",933750],["supportedAmount","Evidence-Supported Amount","currency",784350],["domainDriver","Expense Category","select","Fund expense",["Fund expense","Manager expense","Shared expense"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Allocation policy library case","Fund entity registry case","Vendor invoice ingestion case","Expense category classification case","Manager versus fund test case"]})
]);
